apiVersion: v1
kind: Service
metadata:
  name: customer-ticket-service
spec:
  type: NodePort
  selector:
    app: customer-ticket-api
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080